version: '3.8'

services:
  clinic-pulse-db:
    profiles:
      - prod
      - dev
    image: postgres:14.5
    container_name: clinic-pulse-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - clinic-pulse-db-data:/var/lib/postgresql/data

  clinic-pulse-db-test:
    profiles:
      - test
    image: postgres:14.5
    container_name: clinic-pulse-db-test
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    ports:
      - '54320:5432'
    volumes:
      - ./scripts/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh

  clinic-pulse-redis:
    profiles:
      - prod
      - dev
    container_name: clinic-pulse-redis
    image: redis:6.2.6
    command: >
      --requirepass ${REDIS_AUTH_TOKEN}
    restart: always
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    ports:
      - 127.0.0.1:6379:6379

  clinic-pulse-api:
    profiles:
      - prod
    build: .
    container_name: clinic-pulse-api
    ports:
      - 8080:${API_PORT}
    depends_on:
      - clinic-pulse-db
      - clinic-pulse-redis
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}

volumes:
  clinic-pulse-db-data:
