version: '3.8'

services:
  clinic-pulse-db:
    profiles:
      - prod
      - dev
    image: postgres:14.5
    container_name: clinic-pulse-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - clinic-pulse-db-data:/var/lib/postgresql/data

  clinic-pulse-db-test:
    profiles:
      - test
    image: postgres:14.5
    container_name: clinic-pulse-db-test
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    ports:
      - '54320:5432'
    volumes:
      - ./scripts/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh

  clinic-pulse-api:
    profiles:
      - prod
    build: .
    container_name: clinic-pulse-api
    ports:
      - 8080:${API_PORT}
    depends_on:
      - clinic-pulse-db
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}

volumes:
  clinic-pulse-db-data:
