#!/bin/sh
set -ex

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB_NAME" <<-EOSQL
  CREATE EXTENSION pgcrypto;
	GRANT ALL PRIVILEGES ON DATABASE "$POSTGRES_DB_NAME" TO "$POSTGRES_USER";
EOSQL
