@hostname = http://localhost:10000

@usersPath = {{hostname}}/api/users

### user signin
# @name signin
POST {{usersPath}}/signin
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "123456"
}
###
@accessToken = Bearer {{signin.response.body.token}}

@acupuncturesPath = {{hostname}}/api/acupuncture-treatments

### create acupuncture treatment
POST {{acupuncturesPath}}/
Authorization: {{accessToken}}
Content-Type: application/json
###

### update acupuncture assign bed
@acupuntureId = 4d122970-8e74-49fe-8263-5b823562d02b
PATCH {{acupuncturesPath}}/{{acupuntureId}}
Authorization: {{accessToken}}
Content-Type: application/json
###