@hostname = http://localhost:10000

@usersPath = {{hostname}}/api/users

### user signin
# @name signin
POST {{usersPath}}/signin
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "123456"
}
###
@accessToken = Bearer {{signin.response.body.token}}

@consultationsPath = {{hostname}}/api/consultations

### get consultation list
GET {{consultationsPath}}?limit=25&page=1&startDate=2024-08-01&endDate=2024-08-31
Authorization: {{accessToken}}
Content-Type: application/json
###

### get single consultation 
@consultationId = 4dba5f04-a422-400b-a9cb-848eb77f7988
GET {{consultationsPath}}/{{consultationId}}
Authorization: {{accessToken}}
Content-Type: application/json
###

### get consultation canceled and booking
GET {{consultationsPath}}/canceled_and_booking?granularity=DAY&startDate=2024-05-27&endDate=2024-06-02&clinicId=16458ab0-4bb6-4141-9bf0-6d7398942d9b
Authorization: {{accessToken}}
Content-Type: application/json
###

### get consultation real time count
GET {{consultationsPath}}/real_time_counts?clinicId=16458ab0-4bb6-4141-9bf0-6d7398942d9b&consultationRoomNumber=1
Authorization: {{accessToken}}
Content-Type: application/json
###

### get average waiting time
GET {{consultationsPath}}/average_waiting_time?granularity=DAY&startDate=2024-05-27&endDate=2024-06-02&clinicId=16458ab0-4bb6-4141-9bf0-6d7398942d9b
Authorization: {{accessToken}}
Content-Type: application/json
###

### get first time consultation
GET {{consultationsPath}}/first_time?startDate=2024-07-01&endDate=2024-07-29&clinicId=16458ab0-4bb6-4141-9bf0-6d7398942d9b
Authorization: {{accessToken}}
Content-Type: application/json
###

### get average consultation count
GET {{consultationsPath}}/average_counts?granularity=DAY&startDate=2024-05-27&endDate=2024-06-02&clinicId=16458ab0-4bb6-4141-9bf0-6d7398942d9b
Authorization: {{accessToken}}
Content-Type: application/json
###

### get different treatments 
GET {{consultationsPath}}/different_treatments?granularity=WEEK&startDate=2024-08-01&endDate=2024-08-13&clinicId=16458ab0-4bb6-4141-9bf0-6d7398942d9b
Authorization: {{accessToken}}
Content-Type: application/json
###

### create consultation
POST {{consultationsPath}}/
Authorization: {{accessToken}}
Content-Type: application/json

{
  "patientId":"da3ab31e-fa43-4162-aaf1-71ab66a8f3e6",
  "timeSlotId": "02ec4442-dc2f-4ee4-aa9c-1cfb1d662589"
}
###

### update consultation startAt
@id = 2762e440-3932-47d6-af43-9a5a85888df5
PATCH {{consultationsPath}}/{{id}}/start_at
Authorization: {{accessToken}}
Content-Type: application/json

###

### update consultation onsite cancel at
@cId = 4dba5f04-a422-400b-a9cb-848eb77f7988
PATCH {{consultationsPath}}/{{cId}}/onsite_cancel_at
Authorization: {{accessToken}}
Content-Type: application/json

###

