@hostname = http://localhost:10000

@usersPath = {{hostname}}/api/users

### user signin
# @name signin
POST {{usersPath}}/signin
Content-Type: application/json

{
  "email": "doctor_tsai@example.com",
  "password": "123456"
}
###
@accessToken = Bearer {{signin.response.body.token}}

@doctorsPath = {{hostname}}/api/doctors

### get all doctors
GET {{doctorsPath}}
Authorization: {{accessToken}}
Content-Type: application/json
###


### get doctor profile
@doctorId = 8545ef60-a94d-4160-829f-f4fd7ed77551
GET {{doctorsPath}}/{{doctorId}}
Authorization: {{accessToken}}
Content-Type: application/json
###