@hostname = http://localhost:10000

@usersPath = {{hostname}}/api/users

### user signin
# @name signin
POST {{usersPath}}/signin
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "123456"
}
###
@accessToken = Bearer {{signin.response.body.token}}
@feedbacksPath = {{hostname}}/api/feedbacks
### get feedback list
GET {{feedbacksPath}}?limit=20&page=1&startDate=2024-08-01&endDate=2024-08-29&clinicId=16458ab0-4bb6-4141-9bf0-6d7398942d9b
Authorization: {{accessToken}}
Content-Type: application/json
###

### get single feedback
@feedbackId = 4b790112-8b1e-465a-8ca8-e8f69182fe5b
GET {{feedbacksPath}}/{{feedbackId}}
Authorization: {{accessToken}}
Content-Type: application/json
###

### get feedback rations
GET {{feedbacksPath}}/related_ratios?granularity=WEEK&startDate=2024-08-01&endDate=2024-08-31&clinicId=16458ab0-4bb6-4141-9bf0-6d7398942d9b
Authorization: {{accessToken}}
Content-Type: application/json
###

### create feedback 
POST {{feedbacksPath}}/
Authorization: {{accessToken}}
Content-Type: application/json

{
  "feedbackRating": 3,
  "selectedContent":"LONG_WAIT_TIME_FOR_ACUPUNCTURE",
   "detailedContent": "等候時間太長了，期待改善。",
   "consultationId": "bd2c7e38-c66a-4b30-8832-a52d053f95be"
}
###