@hostname = http://localhost:10000

@usersPath = {{hostname}}/api/users

### user signin
# @name signin
POST {{usersPath}}/signin
Content-Type: application/json

{
  "email": "ann@gmail.com",
  "password": "ann"
}
###
@accessToken = Bearer {{signin.response.body.token}}
@feedbacksPath = {{hostname}}/api/feedbacks
### get feedback list
GET {{feedbacksPath}}?limit=20&page=1&startDate=2024-07-01&endDate=2024-07-29&clinicId=16458ab0-4bb6-4141-9bf0-6d7398942d9b
Authorization: {{accessToken}}
Content-Type: application/json
###

### get single feedback
@feedbackId = 4b790112-8b1e-465a-8ca8-e8f69182fe5b
GET {{feedbacksPath}}/{{feedbackId}}
Authorization: {{accessToken}}
Content-Type: application/json
###

