@hostname = http://localhost:10000

@usersPath = {{hostname}}/api/users

### user signin
# @name signin
POST {{usersPath}}/signin
Content-Type: application/json

{
  "email": "111@gmail.com",
  "password": "111"
}
###
@accessToken = Bearer {{signin.response.body.token}}

@medicinesPath = {{hostname}}/api/medicine-treatments

### create medicine treatment
POST {{medicinesPath}}/
Authorization: {{accessToken}}
Content-Type: application/json
###