@hostname = http://localhost:10000
@usersPath = {{hostname}}/api/users

### Register new user
POST {{usersPath}}
Content-Type: application/json

{
  "email": "ellen@gmail.com",
  "password": "ellen",
  "firstName":null,
  "lastName":null,
  "role": "ADMIN",
  "onboardDate":null,
  "gender":null,
  "birthDate": null,
}
###

### user signin
# @name signin
POST {{usersPath}}/signin
Content-Type: application/json

{
  "email": "111@gmail.com",
  "password": "111"
}
###
@accessToken = Bearer {{signin.response.body.token}}

